//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KON.OScamService {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KON.OScamService.properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        public static string frmConfiguration_BaseTitle {
            get {
                return ResourceManager.GetString("frmConfiguration_BaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save ähnelt.
        /// </summary>
        public static string frmConfiguration_btnSave_Text {
            get {
                return ResourceManager.GetString("frmConfiguration_btnSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AdditionalStartupParameters ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyAdditionalStartupParameters {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyAdditionalStartupParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -d 0 ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyAdditionalStartupParameters_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyAdditionalStartupParameters_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CheckEnable ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyCheckEnable {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyCheckEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die True ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyCheckEnable_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyCheckEnable_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CheckInterval ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyCheckInterval {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10 ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyCheckInterval_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyCheckInterval_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DelayStart ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyDelayStart {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyDelayStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyDelayStart_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyDelayStart_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LogLevel ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyLogLevel {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyLogLevel_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogLevel_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LogToConsole ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyLogToConsole {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogToConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die false ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyLogToConsole_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogToConsole_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VerboseLogging ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyVerboseLogging {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyVerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die false ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyVerboseLogging_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyVerboseLogging_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebServiceTimeout ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceTimeout {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 15 ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceTimeout_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceTimeout_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebServiceUrl ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceUrl {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://localhost:8888/oscamapi.html?part=status ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceUrl_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die oscam.exe ähnelt.
        /// </summary>
        public static string OScamService_BinaryFileName_OScam {
            get {
                return ResourceManager.GetString("OScamService_BinaryFileName_OScam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die oscam ähnelt.
        /// </summary>
        public static string OScamService_BinaryFileTitle_OScam {
            get {
                return ResourceManager.GetString("OScamService_BinaryFileTitle_OScam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Un-/Installing service at ähnelt.
        /// </summary>
        public static string OScamService_Console_UnInstalling {
            get {
                return ResourceManager.GetString("OScamService_Console_UnInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error un-/installing the service: ähnelt.
        /// </summary>
        public static string OScamService_Console_UnInstalling_Error {
            get {
                return ResourceManager.GetString("OScamService_Console_UnInstalling_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restarting &quot;OScam&quot; ähnelt.
        /// </summary>
        public static string OScamService_Global_Logging_RestartOScam {
            get {
                return ResourceManager.GetString("OScamService_Global_Logging_RestartOScam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting &quot;OScam&quot; with the following command: ähnelt.
        /// </summary>
        public static string OScamService_Global_Logging_StartOScam {
            get {
                return ResourceManager.GetString("OScamService_Global_Logging_StartOScam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error starting &quot;OScam&quot; - e.g. &quot;OScam&quot; binary does not exist! ähnelt.
        /// </summary>
        public static string OScamService_Global_Logging_StartOScam_Error {
            get {
                return ResourceManager.GetString("OScamService_Global_Logging_StartOScam_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;OScam&quot; processes are running. Attempting to kill all &quot;OScam&quot; processes. ähnelt.
        /// </summary>
        public static string OScamService_Global_Logging_StopOScam {
            get {
                return ResourceManager.GetString("OScamService_Global_Logging_StopOScam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;OScam&quot; restart not required! ähnelt.
        /// </summary>
        public static string OScamService_OScam_Restart_NotRequired {
            get {
                return ResourceManager.GetString("OScamService_OScam_Restart_NotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;OScam&quot; restart required! ähnelt.
        /// </summary>
        public static string OScamService_OScam_Restart_Required {
            get {
                return ResourceManager.GetString("OScamService_OScam_Restart_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not executed with administrative permissions - expect untested misbehavior! ähnelt.
        /// </summary>
        public static string OScamService_Service_AdministratorRequired {
            get {
                return ResourceManager.GetString("OScamService_Service_AdministratorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        public static string OScamService_Service_LogName {
            get {
                return ResourceManager.GetString("OScamService_Service_LogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KON.OScamService ähnelt.
        /// </summary>
        public static string OScamService_Service_Name {
            get {
                return ResourceManager.GetString("OScamService_Service_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press enter to exit ... ähnelt.
        /// </summary>
        public static string OScamService_Service_RunAsConsole {
            get {
                return ResourceManager.GetString("OScamService_Service_RunAsConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service start delayed! ähnelt.
        /// </summary>
        public static string OScamService_Service_StartDelayed {
            get {
                return ResourceManager.GetString("OScamService_Service_StartDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service start start failed! ähnelt.
        /// </summary>
        public static string OScamService_Service_StartFailed {
            get {
                return ResourceManager.GetString("OScamService_Service_StartFailed", resourceCulture);
            }
        }
    }
}
