//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KON.OScamService {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KON.OScamService.properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        public static string frmConfiguration_BaseTitle {
            get {
                return ResourceManager.GetString("frmConfiguration_BaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save ähnelt.
        /// </summary>
        public static string frmConfiguration_btnSave_Text {
            get {
                return ResourceManager.GetString("frmConfiguration_btnSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AdditionalStartupParameters ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyAdditionalStartupParameters {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyAdditionalStartupParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -d 0 ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyAdditionalStartupParameters_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyAdditionalStartupParameters_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CheckInterval ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyCheckInterval {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10 ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyCheckInterval_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyCheckInterval_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LogLevel ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyLogLevel {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyLogLevel_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogLevel_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LogToConsole ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyLogToConsole {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogToConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die false ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyLogToConsole_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogToConsole_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OScam_BinaryFilename ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyOScam_BinaryFilename {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyOScam_BinaryFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die oscam.exe ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyOScam_BinaryFilename_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyOScam_BinaryFilename_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OScam_BinaryFilepath ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyOScam_BinaryFilepath {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyOScam_BinaryFilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C:\Program Files\KON.OScamService\3rdparty\oscam ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyOScam_BinaryFilepath_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyOScam_BinaryFilepath_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OScam_BinaryTitle ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyOScam_BinaryTitle {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyOScam_BinaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die oscam ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyOScam_BinaryTitle_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyOScam_BinaryTitle_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StartDelay ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyStartDelay {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyStartDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyStartDelay_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyStartDelay_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VerboseLogging ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyVerboseLogging {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyVerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die false ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyVerboseLogging_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyVerboseLogging_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CheckEnable ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceCheckEnable {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceCheckEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die true ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceCheckEnable_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceCheckEnable_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebServiceTimeout ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceTimeout {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 15 ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceTimeout_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceTimeout_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebServiceUrl ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceUrl {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://localhost:8888/oscamapi.html?part=status ähnelt.
        /// </summary>
        public static string frmConfiguration_srsKeyWebServiceUrl_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HttpWebRequest Dispose successful! ähnelt.
        /// </summary>
        public static string OScam_RequestDisposed {
            get {
                return ResourceManager.GetString("OScam_RequestDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HttpWebRequest Time-Out! ähnelt.
        /// </summary>
        public static string OScam_RequestTimedOut {
            get {
                return ResourceManager.GetString("OScam_RequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HttpWebResponse Dispose successful! ähnelt.
        /// </summary>
        public static string OScam_ResponseDisposed {
            get {
                return ResourceManager.GetString("OScam_ResponseDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;OScam&quot; restart not required! ähnelt.
        /// </summary>
        public static string OScam_Restart_NotRequired {
            get {
                return ResourceManager.GetString("OScam_Restart_NotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;OScam&quot; restart required! ähnelt.
        /// </summary>
        public static string OScam_Restart_Required {
            get {
                return ResourceManager.GetString("OScam_Restart_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restarting &quot;OScam&quot; ähnelt.
        /// </summary>
        public static string OScam_RestartOScam {
            get {
                return ResourceManager.GetString("OScam_RestartOScam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service start delayed! ähnelt.
        /// </summary>
        public static string OScam_StartDelayed {
            get {
                return ResourceManager.GetString("OScam_StartDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service start start failed! ähnelt.
        /// </summary>
        public static string OScam_StartFailed {
            get {
                return ResourceManager.GetString("OScam_StartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting &quot;OScam&quot; with the following command: ähnelt.
        /// </summary>
        public static string OScam_StartOScam {
            get {
                return ResourceManager.GetString("OScam_StartOScam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error starting &quot;OScam&quot; - e.g. &quot;OScam&quot; binary does not exist! ähnelt.
        /// </summary>
        public static string OScam_StartOScam_Error {
            get {
                return ResourceManager.GetString("OScam_StartOScam_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;OScam&quot; processes are running. Attempting to kill all &quot;OScam&quot; processes. ähnelt.
        /// </summary>
        public static string OScam_StopOScam {
            get {
                return ResourceManager.GetString("OScam_StopOScam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not executed with administrative permissions - expect untested misbehavior! ähnelt.
        /// </summary>
        public static string Program_AdministratorRequired {
            get {
                return ResourceManager.GetString("Program_AdministratorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows service to start and/or stop OScam binaries. ähnelt.
        /// </summary>
        public static string Program_Description {
            get {
                return ResourceManager.GetString("Program_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KON.OScamService ähnelt.
        /// </summary>
        public static string Program_DisplayName {
            get {
                return ResourceManager.GetString("Program_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        public static string Program_LogName {
            get {
                return ResourceManager.GetString("Program_LogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KON.OScamService ähnelt.
        /// </summary>
        public static string Program_Name {
            get {
                return ResourceManager.GetString("Program_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press enter to exit ... ähnelt.
        /// </summary>
        public static string Program_RunAsConsole {
            get {
                return ResourceManager.GetString("Program_RunAsConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installing service at ähnelt.
        /// </summary>
        public static string Service_Installing {
            get {
                return ResourceManager.GetString("Service_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Un-/Installing service at ähnelt.
        /// </summary>
        public static string Service_Uninstalling {
            get {
                return ResourceManager.GetString("Service_Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error un-/installing the service: ähnelt.
        /// </summary>
        public static string Service_Uninstalling_Error {
            get {
                return ResourceManager.GetString("Service_Uninstalling_Error", resourceCulture);
            }
        }
    }
}
